version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/datab_root_password
      MYSQL_DATABASE: tododb
    secrets:
      - datab_root_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend-net

  backend:
    image: ndondo26/todo-backend:latest
    ports:
      - "8080:80"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_NAME: tododb
    secrets:
      - datab_root_password
    networks:
      - backend-net
      - frontend-net

  frontend:
    image: ndondo26/todo-frontend:latest
    ports:
      - "3000:80"
    networks:
      - frontend-net

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

volumes:
  db-data:

secrets:
  datab_root_password:
    file: ./datab_root_password.txt
